spring:
  application:
    name: gateway
server:
  port: 8080
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true