spring:
  application:
    name: gateway

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

cloud:
  gateway:
    routes:
      # Роутинг для user-service
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
        filters:
          - RewritePath=/users/(?<segment>.*), /api/users/${segment}

      # Роутинг для company-service
      - id: company-service
        uri: lb://company-service
        predicates:
          - Path=/companies/**
        filters:
          - RewritePath=/companies/(?<segment>.*), /api/companies/${segment}
