server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ilgiz
    password: ilgiz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

company:
  service:
    url: http://localhost:8082
