server:
  port: 8081
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ilgiz
    password: ilgiz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

company:
  service:
    url: http://localhost:8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true